version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-net

  backend:
    build: ./backend
    container_name: backend
    restart: always
    environment:
      - MONGO_URL=mongodb://mongo:27017/marketplace
      - JWT_SECRET=supersecret
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    networks:
      - app-net

  chat:
    build: ./chat-server
    container_name: chat
    restart: always
    ports:
      - "4000:4000"
    networks:
      - app-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    depends_on:
      - backend
    networks:
      - app-net

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
      - chat
    networks:
      - app-net

volumes:
  mongo-data:

networks:
  app-net:
